config/routes.rb
Pagamento::Application.routes.draw do
  resources :conformidades

  resources :fornecedores
  
  devise_for :usuarios
  
  resources :usuarios

  root :to => 'conformidades#index'

end

app/models/conformidade.rb
# encoding: utf-8

class Conformidade < ActiveRecord::Base
	belongs_to :fornecedor
	validates :caixa, format: {with: /\d{3}\/20\d{2}/, message: 'use o padrão número/ano (XXX/20XX)'}
	validates :processo, format: {with: /\d{4}\/20\d{2}/, message: 'use o padrão número/ano (XXX/20XX)'}
end

app/models/fornecedor.rb
# encoding: utf-8

require "brcpfcnpj"

class Fornecedor < ActiveRecord::Base
  has_many :conformidades

  validates :nome, presence: true
  validates :cnpj, presence: true, if: :pj?
  validates :cpf, presence: true, unless: :pj?
  validates_uniqueness_of :cnpj, :cpf
  usar_como_cpf :cpf
  usar_como_cnpj :cnpj
  validate :cpf_ou_cnpj

  private
    def cpf_ou_cnpj
      if cpf.present? and cnpj.present?
        errors[:base] << "Use CNPJ ou CPF."
      end

      if cpf.blank? and cnpj.blank?
        errors[:base] << "Use ao menos CNPJ ou CPF."
      end
    end
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/conformidades_controller.rb
class ConformidadesController < ApplicationController
  before_filter :authenticate_usuario!, except: [:index, :show]
  # GET /conformidades
  # GET /conformidades.json
  def index
    @conformidades = Conformidade.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @conformidades }
    end
  end

  # GET /conformidades/1
  # GET /conformidades/1.json
  def show
    @conformidade = Conformidade.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @conformidade }
    end
  end

  # GET /conformidades/new
  # GET /conformidades/new.json
  def new
    @conformidade = Conformidade.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @conformidade }
    end
  end

  # GET /conformidades/1/edit
  def edit
    @conformidade = Conformidade.find(params[:id])
  end

  # POST /conformidades
  # POST /conformidades.json
  def create
    @conformidade = Conformidade.new(params[:conformidade])

    respond_to do |format|
      if @conformidade.save
        format.html { redirect_to @conformidade, notice: 'Conformidade was successfully created.' }
        format.json { render json: @conformidade, status: :created, location: @conformidade }
      else
        format.html { render action: "new" }
        format.json { render json: @conformidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /conformidades/1
  # PUT /conformidades/1.json
  def update
    @conformidade = Conformidade.find(params[:id])

    respond_to do |format|
      if @conformidade.update_attributes(params[:conformidade])
        format.html { redirect_to @conformidade, notice: 'Conformidade was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @conformidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conformidades/1
  # DELETE /conformidades/1.json
  def destroy
    @conformidade = Conformidade.find(params[:id])
    @conformidade.destroy

    respond_to do |format|
      format.html { redirect_to conformidades_url }
      format.json { head :ok }
    end
  end
end

app/controllers/fornecedores_controller.rb
# encoding: utf-8

class FornecedoresController < ApplicationController
  before_filter :authenticate_usuario!, except: [:index]

  # GET /fornecedores
  def index
    @fornecedores = Fornecedor.page(params[:page]).per(2)
  end

  # GET /fornecedores/1
  def show
    @fornecedor = Fornecedor.find(params[:id])
  end

  # GET /fornecedores/new
  def new
    @fornecedor = Fornecedor.new
  end

  # GET /fornecedores/1/edit
  def edit
    @fornecedor = Fornecedor.find(params[:id])
  end

  # POST /fornecedores
  def create
    @fornecedor = Fornecedor.new(params[:fornecedor])

    if @fornecedor.save
      redirect_to fornecedores_path, notice: 'Fornecedor foi criado.'
    else
      render action: "new"
    end
  end

  # PUT /fornecedores/1
  def update
    @fornecedor = Fornecedor.find(params[:id])

    if @fornecedor.update_attributes(params[:fornecedor])
      redirect_to fornecedores_path, notice: 'Fornecedor foi atualizado.'
    else
      render action: "edit"
    end
  end

  # DELETE /fornecedores/1
  def destroy
    @fornecedor = Fornecedor.find(params[:id])
    @fornecedor.destroy

    redirect_to fornecedores_path, notice: 'Fornecedor foi excluído.'
  end
end

app/controllers/usuarios_controller.rb
# encoding: utf-8

class UsuariosController < ApplicationController
  before_filter :authenticate_usuario!

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @usuarios }
    end
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
    @usuario = Usuario.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @usuario }
    end
  end

  # GET /usuarios/new
  # GET /usuarios/new.json
  def new
    @usuario = Usuario.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @usuario }
    end
  end

  # GET /usuarios/1/edit
  def edit
    @usuario = Usuario.find(params[:id])
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(params[:usuario])

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuário criado com sucesso.' }
        format.json { render json: @usuario, status: :created, location: @usuario }
      else
        format.html { render action: "new" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /usuarios/1
  # PUT /usuarios/1.json
  def update
    @usuario = Usuario.find(params[:id])

    respond_to do |format|
      if @usuario.update_attributes(params[:usuario])
        format.html { redirect_to @usuario, notice: 'Usuário alterado com sucesso.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario = Usuario.find(params[:id])
    @usuario.destroy

    respond_to do |format|
      format.html { redirect_to usuarios_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conformidades_helper.rb
module ConformidadesHelper
end

app/helpers/fornecedores_helper.rb
module FornecedoresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/conformidades/_form.html.erb
<%= form_for(@conformidade) do |f| %>
  <% if @conformidade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conformidade.errors.count, "error") %> prohibited this conformidade from being saved:</h2>

      <ul>
      <% @conformidade.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :caixa %><br />
    <%= f.text_field :caixa %>
  </div>
  <div class="field">
    <%= f.label :processo %><br />
    <%= f.text_field :processo %>
  </div>
  <div class="field">
    <%= f.label :data %><br />
    <%= f.text_field :data, value: localize(@conformidade.data||Date.today) %>
  </div>
  <div class="field">
    <%= f.label :fornecedor %><br />
    <%= f.collection_select :fornecedor_id, Fornecedor.all, :id, :nome %>
  </div>
  <div class="field">
    <%= f.label :valor %><br />
    <%= f.text_field :valor %>
  </div>
  <div class="field">
    <%= f.label :publicado %><br />
    <%= f.check_box :publicado %>
  </div>
  <div class="field">
    <%= f.label 'observação' %><br />
    <%= f.text_area :observacao %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/conformidades/edit.html.erb
<h1>Editar conformidade</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @conformidade %> |
<%= link_to 'Voltar', conformidades_path %>

app/views/conformidades/index.html.erb
<h1>Lista de conformidades</h1>

<table>
  <tr>
    <th>Caixa</th>
    <th>Precesso</th>
    <th>Data</th>
    <th>Valor</th>
    <th>Fornecedor</th>
    <th>Publicado</th>
    <th></th>
    <% if usuario_signed_in? %>
        <th></th>
        <th></th>
    <% end %>
  </tr>

<% @conformidades.each do |conformidade| %>
  <tr>
    <td><%= conformidade.caixa %></td>
    <td><%= conformidade.processo %></td>
    <td><%= localize conformidade.data %></td>
    <td><%=  number_to_currency conformidade.valor %></td>
    <td><%= conformidade.fornecedor.nome %></td>
    <td><%= conformidade.publicado? ? 'Sim' : 'Não' %></td>
    <td><%= link_to 'Detalhes', conformidade %></td>
    <% if usuario_signed_in? %>
        <td><%= link_to 'Editar', edit_conformidade_path(conformidade) %></td>
        <td><%= link_to 'Excluir', conformidade, confirm: 'Tem certeza?', method: :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />
<% if usuario_signed_in? %>
    <%= link_to 'Nova Conformidade', new_conformidade_path %>
<% end %>

app/views/conformidades/new.html.erb
<h1>Nova conformidade</h1>

<%= render 'form' %>

<%= link_to 'Voltar', conformidades_path %>

app/views/conformidades/show.html.erb
<p>
  <b>Caixa:</b>
  <%= @conformidade.caixa %>
</p>

<p>
  <b>Processo:</b>
  <%= @conformidade.processo %>
</p>
<p>
  <b>Data:</b>
  <%= localize @conformidade.data %>
</p>
<p>
  <b>Observação:</b>
  <%= @conformidade.observacao %>
</p>
<p>
  <b>Valor:</b>
  <%= number_to_currency @conformidade.valor %>
</p>
<p>
  <b>Fornecedor:</b>
  <%= @conformidade.fornecedor.nome %>
</p>

<% if usuario_signed_in? %>
  <%= link_to 'Editar', edit_conformidade_path(@conformidade) %> |
<% end %>
<%= link_to 'Voltar', conformidades_path %>

app/views/fornecedores/_form.html.erb
<%= form_for(@fornecedor) do |f| %>
  <% if @fornecedor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fornecedor.errors.count, "error") %> prohibited this fornecedor from being saved:</h2>

      <ul>
      <% @fornecedor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label 'Pessoa Jurídica?' %><br />
    <%= f.check_box :pj %>
  </div>

  <div id="cpf" class="field">
    <%= f.label 'CPF' %><br />
    <%= f.text_field :cpf %>
  </div>

  <div id="cnpj" class="field">
    <%= f.label 'CNPJ' %><br />
    <%= f.text_field :cnpj %>
  </div>
  <div class="field">
    <%= f.label :publicado %><br />
    <%= f.check_box :publicado %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fornecedores/edit.html.erb
<h1>Editar fornecedor</h1>

<%= render 'form' %>

<%= link_to 'Voltar', fornecedores_path %>

app/views/fornecedores/index.html.erb
<h1>Fornecedores</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>CNPJ/CPF</th>
    <th>Pessoa jurídica</th>
    <th>Publicado</th>
    <th></th>
    <th></th>
  </tr>

<% @fornecedores.each do |fornecedor| %>
  <tr>
    <td><%= fornecedor.nome %></td>
    <td><%= fornecedor.pj? ? fornecedor.cnpj : fornecedor.cpf %></td>
    <td><%= fornecedor.pj? ? 'Sim' : 'Não' %></td>
    <td><%= fornecedor.publicado? ? 'Sim' : 'Não' %></td>

    <% if usuario_signed_in? %>
      <td><%= link_to 'Editar', edit_fornecedor_path(fornecedor) %></td>
      <td><%= link_to 'Excluir', fornecedor, confirm: 'Tem certeza?', method: :delete %></td>
    <% else %>
      <td></td>
      <td></td>
    <% end %>
    
  </tr>
<% end %>
</table>

<%= paginate @fornecedores %>

<br />

<% if usuario_signed_in? %>
  <%= link_to 'Novo Fornecedor', new_fornecedor_path %>
<% end %>

app/views/fornecedores/new.html.erb
<h1>Novo fornecedor</h1>

<%= render 'form' %>

<%= link_to 'Voltar', fornecedores_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pagamento</title>
  <%= stylesheet_link_tag    "application", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/base/jquery-ui.css" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!--[if (gte IE 6)&(lte IE 8)]>
	  <%= javascript_include_tag "http://s3.amazonaws.com/nwapi/nwmatcher/nwmatcher-1.2.4-min.js", "selectivizr" %>
	<![endif]-->
</head>
<body>

<div class="usuario">
	<% if usuario_signed_in? %>
	<%= link_to 'Sair', destroy_usuario_session_path, method: :delete %>
	<% else %>
	<%= link_to 'Entrar', new_usuario_session_path %>
	<% end %>
</div>

<nav>
	<%= link_to 'Conformidades', conformidades_path %> |
	<%= link_to 'Fornecedores', fornecedores_path %>
	<% if usuario_signed_in? %>
		| <%= link_to 'Usuários', usuarios_path %> 
	<% end %>
</nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editar usuario</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @usuario %> |
<%= link_to 'Voltar', usuarios_path %>

app/views/usuarios/index.html.erb
<h1>Lista de usuarios</h1>

<table>
  <tr>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @usuarios.each do |usuario| %>
  <tr>
    <td><%= usuario.email %></td>
    <td><%= link_to 'Editar', edit_usuario_path(usuario) %></td>
    <td><%= link_to 'Excluir', usuario, confirm: 'Tem certeza?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Novo Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>Novo usuario</h1>

<%= render 'form' %>

<%= link_to 'Voltar', usuarios_path %>

app/views/usuarios/show.html.erb
<p>
  <b>Email:</b>
  <%= @usuario.email %>
</p>

<%= link_to 'Editar', edit_usuario_path(@usuario) %> |
<%= link_to 'Voltar', usuarios_path %>